删除deserializer中是否为json的判断
Lambdua/openai4j pull request #29
Opened 2024-05-23 12:18 UTC by I-am-DJ

删除deserializer中是否为json的判断
openaiservice中function call对象改为了局部变量，qwen流式返回function call时，最后一个会带有finishReason但是没有具体的function call结果，导致重复进入解析，所以改为局部变量进行判断

2024-05-24 01:38 UTC, Lambdua commented
deserializer中的json判断不能删除,该反序列方法,不仅仅适用于stream接口. 非stream接口也是走的这个

2024-05-24 01:45 UTC, Lambdua commented
不过这边的json校验方法是需要优化一下,不能每次创建mapper实例

2024-05-24 01:53 UTC, Lambdua requested changes
- deserializer中的json判断不能删除,该反序列方法,不仅仅适用于stream接口. 非stream接口也是走的这个.所以需要判断,不过这边的json校验方法是需要优化一下,不能每次创建mapper实例
- openaiService修改部分,是否有跑通过单元测试,我这边跑不通

2024-05-27 01:12 UTC, closed without merging

2024-05-28 05:41 UTC, I-am-DJ commented
这两天生病了，能方便加下其他联系方式吗？我尝试看下用chatgpt的api能否访问

2024-05-28 09:37 UTC, xyifhgvnlo286 commented
微信: lt547670718